FROM nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04 as base

# Ignore interactive questions during `docker build`
ENV DEBIAN_FRONTEND noninteractive

# Bash shell
RUN chsh -s /bin/bash
SHELL ["/bin/bash", "-c"]

# Versions
ARG TORCH_CUDA_VERSION=cu116
ARG TORCH_VERSION=1.13.1
ARG TORCHVISION_VERSION=0.14.1

# Install and update tools to minimize security vulnerabilities
RUN apt-get update
RUN apt-get install -y software-properties-common wget apt-utils patchelf git libprotobuf-dev protobuf-compiler cmake \
    bzip2 ca-certificates libglib2.0-0 libxext6 libsm6 libxrender1 mercurial subversion libopenmpi-dev && \
    apt-get clean
RUN unattended-upgrade
RUN apt-get autoremove -y

# Install Pythyon (3.8 as default)
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1
RUN apt-get install -y python3-pip
RUN update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
RUN pip install -U pip
RUN pip install pygit2 pgzip


FROM base as data

WORKDIR /build
COPY requirements.txt /build/requirements.txt
RUN python3 --version
RUN pip3 install --upgrade pip setuptools wheel cython
RUN pip3 install -r requirements.txt